# Generated by Django 2.2 on 2021-03-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Searches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Client IP Address')),
                ('search', models.TextField(verbose_name='Search term')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
