# Generated by Django 2.2 on 2021-03-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searches',
            options={'verbose_name': 'Searches', 'verbose_name_plural': 'Searches'},
        ),
    ]
